name: First Workflow

on: push

jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Welcome message
        run: echo "Welcome from GitHub Actions"
      
      - name: List files
        run: ls


