name: First Workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout repo
        uses: actions/checkout@v4 

      - name: Welcome message
        run: echo "Welcome from GitHub Actions"
        
      - name: Run test script
        run: ./test-script.sh
    
      